### ISSUE TITLE
How to Decrypt Login Data ????

### ISSUE THREAD

**Issue by onemask1309** [Takaovi/BSBuilder#6]
How to Decrypt Login Data ???? That We Recived bro ??

**Comment by Takaovi** [comment]
Can't currently. It needs to be done locally. If you want to get the data, you should try other scripts done in Python.

I will update the script when and if I make it decrypt the data, but it might take a while as batch files have almost no functionality, so I need to find some .exe or VBA script to do that for me, those are usually detected though so...
